# General config

# Commands can be dynamically defined here, to open specific forms.
commands:
  # The command name
  servers:
    method: register
    # Target both bedrock and java players
    all:
      open: servers

    permission:
      key: crossplatforms.shortcut.servers
      description: "Open the servers list"
      default: true

# Toggle debug logging
enable-debug: false

# Don't touch this
config-version: 1
