# GServerSelector by Jens & Konicai


# Gives the player a compass which they can use to open the selector form
ItemJoin: true
Slot: 4
# Stop the player from dropping the compass
AllowItemDrop: false
# Destroy the compass if the player drops it
DestroyDroppedItem: true
# Stop the player from moving the compass
AllowItemMove: false

# Toggle debug logging
EnableDebug: false

# Don't touch this
ConfigVersion: 2


# Please see our readme for information on configuring this section.
# https://github.com/ProjectG-Plugins/GeyserServerSelector#Configuration
Form:

  Title: "Server Selector"
  Content: "Click on the server button of choice."

  Servers:
    Lobby:
      ButtonText: "Server Lobby"
      ImageURL: "https://www.digminecraft.com/block_recipes/images/cyan_concrete.png"
    Survival:
      ButtonText: "Survival of the fittest"
      ImageURL: "https://www.digminecraft.com/block_recipes/images/blue_concrete.png"
    Creative:
      ButtonText: "Creative Plots"
      ImageURL: "https://www.digminecraft.com/block_recipes/images/purple_concrete.png"
    Factions:
      ButtonText: "Factions - In Progress!"
      ImageURL: "https://www.digminecraft.com/block_recipes/images/magenta_concrete.png"
  Commands:
    ExtraOne:
      ButtonText: "Spawn"
      ImageURL: "https://www.digminecraft.com/decoration_recipes/images/lodestone.png"
      Commands:
        - "execute as {playerName} run spawn"
    ExtraTwo:
      ButtonText: "The Void"
      ImageURL: "https://www.digminecraft.com/block_recipes/images/black_concrete.png"
      Commands:
        - "tp {playerName} 0 -10 0"
        - "say {playerName} made a fatal decision."