# GServerSelector by Jens

# Enable Selector
EnableSelector: true

# Gives player compass and options
ItemJoin: true
Slot: 4
DisableItemDrop: true
DisableItemMove: true

# Edit Selector Form
Form:

  Title: Server Selector
  Content: Click on the server button of choice.

# Add as many servers as you want. Replace "ButtonTextHere" with the text you want on the button.
# The ServerName value must be the exact server name defined in bungeecord's config.
# If you remove the ImageURL key, no icon will be shown next to the button.
  Servers:
    ButtonTextHere:
      ServerName: Lobby
      ImageURL: "https://www.digminecraft.com/block_recipes/images/cyan_concrete.png"
    Survival:
      ServerName: Survival
      ImageURL: "https://www.digminecraft.com/block_recipes/images/blue_concrete.png"
    Creative:
      ServerName: Creative
      ImageURL: "https://www.digminecraft.com/block_recipes/images/purple_concrete.png"
    Factions:
      ServerName: Factions
      ImageURL: "https://www.digminecraft.com/block_recipes/images/magenta_concrete.png"