# BedrockServerSelector by Jens

# Enable Selector
EnableSelector: true

# Gives player compass and options
ItemJoin: true
Slot: 4

# Edit Selector Form
Form:

  Title: Server Selector
  Content: Click on the server button of choice.

# Button Titles
  Button1: Lobby
  Button2: Survival
  Button3: Creative
  Button4: Factions
  Button5: MiniGames

# Define Bungeecord ServerNames. has to be exact the same as in the bungeecord config.yml!
  ServerName1: Lobby
  ServerName2: Survival
  ServerName3: Creative
  ServerName4: Factions
  ServerName5: Minigames

# Button Images Paths
  Path1: dirt.png
  Path2: cobble.png
  Path3: diamond.png
  Path4: emerald.png
  Path5: gold.png