# GServerSelector by Jens

# Enable Selector
EnableSelector: true

# Gives player compass and options
ItemJoin: true
Slot: 4
DisableItemDrop: true
DisableItemMove: true

# Edit Selector Form
Form:

  Title: "Server Selector"
  Content: "Click on the server button of choice."

# Add as many servers as you want. The name of the server must be the exact server name defined in bungeecord's config.
# ButtonText is the text that will be shown on the button.
# If you remove the ImageURL key, no icon will be shown to the left of the button.
  Servers:
    Lobby:
      ButtonText: "Server Lobby"
      ImageURL: "https://www.digminecraft.com/block_recipes/images/cyan_concrete.png"
    Survival:
      ButtonText: "Survival of the fittest"
      ImageURL: "https://www.digminecraft.com/block_recipes/images/blue_concrete.png"
    Creative:
      ButtonText: "Creative Plots"
      ImageURL: "https://www.digminecraft.com/block_recipes/images/purple_concrete.png"
    Factions:
      ButtonText: "Factions - In Progress!"
      ImageURL: "https://www.digminecraft.com/block_recipes/images/magenta_concrete.png"