# GeyserHub by Jens & Konicai

# Toggle debug logging
Enable-Debug: false

# Don't touch this
Config-Version: 4


# Gives the player a compass which they can use to open the selector form
Item-Join: true
# The slot in which the item will be given
Slot: 4
# Stop the player from dropping the compass
Allow-Item-Drop: false
# Destroy the compass if the player drops it
Destroy-Dropped-Item: true
# Stop the player from moving the compass
Allow-Item-Move: false

# Please see our readme for information on configuring this section.
# https://github.com/ProjectG-Plugins/GeyserServerSelector#Configuration
Java-Selector:
  Enable: true

  Title: "Server Selector"
  Size: 9

  Servers:
    lobby:
      Display-Name: "Lobby"
      Material: Diamond
      Lore:
        - "&2Online players: %bungee_lobby%"
      Slot: 2
    survival:
      Display-Name: "Survival"
      Material: Emerald
      Lore:
        - "&2online players: %bungee_survival%"
      Slot: 6

Bedrock-Selector:
  Enable: true

  Title: "Server Selector"
  Content: "Click on the server button of choice."

  Servers:
    lobby:
      Button-Text: "Server Lobby: %bungee_lobby% players"
      ImageURL: "https://www.digminecraft.com/block_recipes/images/cyan_concrete.png"
    survival:
      Button-Text: "Survival: %bungee_survival% players"
      ImageURL: "https://www.digminecraft.com/block_recipes/images/blue_concrete.png"
  Commands:
    extraOne:
      Button-Text: "Spawn"
      ImageURL: "https://www.digminecraft.com/decoration_recipes/images/lodestone.png"
      Commands:
        - "execute as %player_name% run spawn"
    extraTwo:
      Button-Text: "The Void"
      Commands:
        - "tp %player_uuid% 0 -10 0"
        - "say %player_name% made a fatal decision."

# Join and leave messages. Supports papi placeholders.
Join-Message:
  Enable: true
  Messages:
    - "&fWelcome &6%player_name%&f on geyser network!"
    - "&bHave a great time playing on our network!"

Join-Teleporter:
  Enable: false
  World: world
  Coordinates: 0;65;0

Scoreboard:
  Enable: true
  # Refresh rate in seconds.
  Refresh-rate: 7
  Title: "Welcome to GeyserServer"
  Lines:
    - "&f+----------------------+"
    - "&f+&b          GeyserLobby      &f+"
    - "&f+&b      Plugin provided by &f   +"
    - "&f+&b            ProjectG.        &f +"
    - "&f&f+----------------------+"
    - "&a  *  &6https://projectg.dev  &a*"


Broadcasts:
  Enable: true
  # ticks between each broadcast (default: 3 minutes)
  Interval: 3600
  Messages:
    Message1:
      - '&6 -*-*-  Welcome to GeyserNetwork  -*-*- '
    Message2:
      - '&6*----------------*----------------* '
      - '&b -*-*-*- GeyserHub -*-*-*-'
      - '&b -*-*- Made by ProjectG -*-*-'
      - '&6*----------------*----------------* '

World-settings:
  disable-hunger-loss: true
  disable-fall-damage: true
  disable-drowning: true
  disable-fire-damage: true
  disable-player-pvp: true
  disable-weather-change: true
  disable-mob-spawning: true
  disable-block-burn: true
  disable-block-fire-spread: true
  disable_block-leaf-decay: true
  disable-block-place: true
  disable-block-break: true