# GeyserHub by Jens & Konicai

# Toggle debug logging
Enable-Debug: false

# Join and leave messages. Supports papi placeholders.
Join-Message:
  Enable: true
  Messages:
    - "§fWelcome §6%player_name%§f on geyser network!"
    - "§bHave a great time playing on our network!"

Join-Teleporter:
  Enable: false
  World: world
  Coordinates: 0;65;0

# The message to be sent to players whenever they are moving to a new server using a button in a form/meu
# which uses the Server functionality. Supports papi placeholders, as well as %server%, the name of the server they are moving to.
Bungeecord-Message: "§fTeleporting to §b%server%"

Scoreboard:
  Enable: true
  # Refresh rate in seconds.
  Refresh-rate: 7
  Title: "Welcome to GeyserServer"
  Lines:
    - "§f+----------------------+"
    - "§f+§b          GeyserLobby      §f+"
    - "§f+§b      Plugin provided by §f   +"
    - "§f+§b            ProjectG.        §f +"
    - "§f§f+----------------------+"
    - "§a  *  §6https://projectg.dev  §a*"


Broadcasts:
  Enable: true
  # ticks between each broadcast (default: 3 minutes)
  Interval: 3600
  Messages:
    Message1:
      - '§6 -*-*-  Welcome to GeyserNetwork  -*-*- '
    Message2:
      - '§6*----------------*----------------* '
      - '§b -*-*-*- GeyserHub -*-*-*-'
      - '§b -*-*- Made by ProjectG -*-*-'
      - '§6*----------------*----------------* '

World-settings:
  disable-hunger-loss: true
  disable-fall-damage: true
  disable-drowning: true
  disable-fire-damage: true
  disable-player-pvp: true
  disable-weather-change: true
  disable-mob-spawning: true
  disable-block-burn: true
  disable-block-fire-spread: true
  disable_block-leaf-decay: true
  disable-block-place: true
  disable-block-break: true

# Don't touch this
Config-Version: 5
