main: dev.projectg.crossplatforms.CrossplatForms
name: ${project.name}
version: ${project.version}
api-version: 1.14
description: Unifies inventory menus with Bedrock Edition forms.
softdepend:
  - Geyser-Spigot
  - floodgate
  - PlaceholderAPI

commands:
  forms:
    description: Base command for CrossplatForms
    permission: crossplatforms

permissions:
  crossplatforms.base:
    description: Access to the base command /forms. Opens the default form if a player runs the command.
    default: true
  crossplatforms.form:
    description: Access to /crossplatform forms open <form>
    default: true
  crossplatforms.form.others:
    description: Access to /crossplatform forms open <form> <playername>
    default: op
  crossplatforms.reload:
    description: Access to /crossplatform reload
    default: op
