name: GServerSelector
main: com.alysaa.serverselector.GServerSelector
version: 1.0
api-version: 1.15
description: Geyser Plugin Addon.
commands:
  servers:
    description: updating Geyser command
    permission: gserverselector.servers
    aliases: /servers