main: dev.projectg.crossplatforms.CrossplatForms
name: ${project.name}
version: ${project.version}
api-version: 1.14
description: Unifies inventory menus with Bedrock Edition forms.
softdepend:
  - Geyser-Spigot
  - floodgate
  - PlaceholderAPI

commands:
  forms:
    description: Base command for CrossplatForms
    permission: crossplatforms.forms

permissions:
  crossplatforms.base:
    description: Access to the base command /forms
    default: true
  crossplatforms.identify:
    description: Access to /forms identify <player
    default: true
  crossplatforms.open:
    description: Access to /forms open <form>
    default: true
  crossplatforms.open.others:
    description: Access to /forms open <form> <playername>
    default: op
  crossplatforms.reload:
    description: Access to /forms reload
    default: op
  crossplatforms.version:
    description: Access to /forms version
    default: op
