main: dev.projectg.geyserhub.GeyserHubMain
name: GeyserHub
version: 1.3.0
api-version: 1.16
description: A crossplay compatible lobby plugin

depend:
  - floodgate
softdepend:
  - PlaceholderAPI

commands:
  ghub:
    description: General command
    permission: geyserhub.main

permissions:
  geyserhub.main:
    description: Access to the base command /ghub. Opens the default form if a player runs the command.
    default: true
  geyserhub.form:
    description: Access to /ghub form <form>
    default: true
  geyserhub.form.others:
    description: Access to /ghub form <form> <playername>
    default: op
  geyserhub.reload:
    description: Access to /ghub reload
    default: op
  geyserhub.blockbreak:
    description: Allows player to break blocks
    default: op
  geyserhub.blockplace:
    description: Allows player to place blocks
    default: op
