name: GeyserHub
main: dev.projectg.serverselector.GeyserHubMain
version: 1.1.0
api-version: 1.13
depend:
  - floodgate
description: Allow Floodgate players to join BungeeCord servers through a Bedrock form.
commands:
  gteleporter:
    description: Open a server selector form.
    permission: gserverselector.teleporter
  gssreload:
    description: Reload the selector form.
    permission: gserverselector.reload