name: GServerSelector
main: com.alysaa.serverselector.GServerSelector
version: 1.0
api-version: 1.13
depend:
  - floodgate
description: Allow Floodgate players to join BungeeCord servers through a Bedrock form.
commands:
  gservers:
    description: Open a server selector form.
    permission: gserverselector.gservers
  gserversreload:
    description: Reload the selector form.