name: GeyserHub
main: dev.projectg.geyserhub.GeyserHubMain
version: 1.1.0
api-version: 1.16
depend:
  - floodgate
description: An crossplay compatible lobby plugin
commands:
  ghteleporter:
    description: Open a server selector form.
    permission: geyserhub.teleporter
  ghreload:
    description: Reload the selector form.
    permission: geyserhub.reload
permissions:
  geyserhub.blockbreak:
    description: Allows player to break blocks
    default: op
  geyserhub.blockplace:
    description: Allows player to place blocks
    default: op