main: dev.projectg.geyserhub.GeyserHubMain
name: GeyserHub
version: 1.2.0
api-version: 1.16
description: A crossplay compatible lobby plugin

depend:
  - floodgate
softdepend:
  - PlaceholderAPI

commands:
  ghteleporter:
    description: Open a server selector form.
    permission: geyserhub.teleporter
  ghreload:
    description: Reload the selector form.
    permission: geyserhub.reload
permissions:
  geyserhub.blockbreak:
    description: Allows player to break blocks
    default: op
  geyserhub.blockplace:
    description: Allows player to place blocks
    default: op